### ISSUE TITLE
"cannot import name QsciScintilla" on Windows 10 & IDA Pro 7.2

### ISSUE THREAD

**Issue by AndreaNaspi** [techbliss/Python_editor#12]
Hi,

I'm trying to install this plugin on my Ida Pro 7.2.

I have successfully uploaded all files to "Program Files\IDA 7.2\python\" folder overwriting my PyQT5 folder. I also loaded the specific plugin in the folder "Program Files\IDA 7.2\plugins\" but when I go to run the plugin it gives me this error:

`Traceback (most recent call last):
  File "C:\Program Files\IDA 7.2\python\ida_idaapi.py", line 572, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files/IDA 7.2/plugins/Code editor/pyeditor.py", line 65, in <module>
    from PyQt5.Qsci import QsciScintilla, QsciLexerPython
ImportError: cannot import name QsciScintilla`

it looks like it can load the QtCore and QtGui modules but can't find the QsciScintilla module.

How can I solve this problem?

Thanks in advance.

**Comment by techbliss** [comment]
delete the QT ones from ida pro installation and replace with my files
